### ISSUE TITLE
confused about how to make it work

### ISSUE THREAD

**Issue by freereaper** [tungel/dotfiles#1]
Hi, the settings that your video show are so wonderful, I follow the steps in README.md,but it does not  work, can you offer me more details about how to set up this, thank you, best Regards.

**Comment by tungel** [comment]
I'm not sure which part that you tried didn't work? Currently this repo is more active in `neovim` branch ( https://github.com/everbot/dotfiles/tree/neovim )

I've updated the `README.md` file to make it a little bit clearer. Feel free to comment here and I'll try to help.

Cheers.

**Comment by freereaper** [comment]
Hi, you see, the airline displays  with strange character, and in vim  everytime I press Tab key there is ^a, and I have tried my best to solve this issue. So , can you give me some sugestions. Thank you!

![Uploading image.png…]()

**Comment by freereaper** [comment]
However, I figure it out that only when I open another urxvt in a existing urxvt terminal, vim airline works properly in the reopened urxvt.But what does the magic, I tried to print the uxrvt settings  and found they are the same, can you help me !

**Comment by tungel** [comment]
I'm not sure. But after install the powerline font and edited your `.Xresources` file, you should run:

```
$ fc-cache -fv
$ xrdb -merge ~/.Xresources
```

**Comment by freereaper** [comment]
I have tried this method, but it does not work at all. Appreciate  for your help.
